### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by levilugato** [osalkk/aws_ec2_unused_resources#1]
Hello, your script has been very useful to me and I would like to add some little features (ELBsv2 and AMIs)

please, let me know if you would like some contribution

Thanks @osalkk

**Comment by osalkk** [comment]
Hey Levi, please feel free to add so we can help the community. I'm so glad it helped you 👍

**Comment by levilugato** [comment]
Great, it's a pleasure to contribute, I am getting 403 to submit the PR, would u need to allow push or stuff like that?

**Comment by osalkk** [comment]
Done, you should get an invite now
